site_name: T-Stick Docs
site_url: https://idmil.github.io/tstick-docs/
repo_url: https://github.com/IDMIL/T-Stick
repo_name: IDMIL/T-Stick
copyright: Copyright &copy; 2018 - 2024 Input Devices and Music Interaction Laboratory, Schulich School of Music, McGill University
theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: Images/favicon.ico
  logo: Images/logo.png
  features:
    - navigation.tabs
    - navigation.footer
    - search.suggest
    - search.highlight
plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions: 
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

#page tree
nav:
  - Home: index.md
  - Getting Started:
    - getting-started/index.md
  - Setup:
    - setup/index.md
    - Changing communication protocols: setup/wireless-settings.md
    - Changing sensor settings: setup/advanced-settings.md
  - Technical Documentation:
    - T-Stick Design Guidelines: engineering/design-guidelines.md
    - T-Stick 5GW Design Requirements: engineering/requirements.md
    - T-Stick 4GW/5GW Functions: engineering/functions.md
    - T-Stick Gestures: engineering/gestures.md
  - Design Documentation:
    - 4th Generation T-Sticks:
      - designs/tstick-4gw/index.md 
      - Variants:
        - T-Stick 4GW-2018: designs/tstick-4gw/specs_4gw_2018.md
        - T-Stick 4GW-2021: designs/tstick-4gw/specs_4gw_2021.md
      - Guides:
        - Build Guide: designs/tstick-4gw/build-guide.md
        - Flashing Guide: designs/tstick-4gw/flashing-guide.md
        - Connecting Guide: designs/tstick-4gw/connection-guide.md
    - 5th Generation T-Sticks: 
      - designs/tstick-5gw/index.md
      - Variants:
        - T-Stick 5GW-Trill: designs/tstick-5gw/specs_5gw_trill.md
        - T-Stick 5GW-Enchanti: designs/tstick-5gw/specs_5gw_enchanti.md
      - Guides:
        - Build Guide: designs/tstick-5gw/build-guide.md
        - Flashing Guide: designs/tstick-5gw/flashing-guide.md
        - Connecting Guide: designs/tstick-5gw/connection-guide.md
  - Community:
    - Performances: community/performances.md
    - Publications: community/publications.md
    - Contribute to the Docs: community/contribution.md